apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: ui-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ui-service
  template:
    metadata:
      labels:
        app: ui-service
    spec:
        containers:
        - name: ui-service
          image: sibosend/ui-service:latest
          imagePullPolicy: Never
          env:
          - name: UPDATED_AT
            value: "Tue 17 Jul 2019 08:26:39 GMT"
          ports:
          - containerPort: 80
            name: ui-port
